import 'dart:async';
import 'dart:io';
import 'dart:math' as math;

import 'package:file_picker/file_picker.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_autofill_service/flutter_autofill_service.dart';
import 'package:flutter/services.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:get_it/get_it.dart';
import 'package:mobile_scanner/mobile_scanner.dart';
import 'package:path/path.dart' as path;

import '../../../../../core/navigation/app_navigation.dart';
import '../../../../../core/responsive/breakpoints.dart';
import '../../../../../core/theme/app_backgrounds.dart';
import '../../../../../core/theme/app_colors.dart';
import '../../../../../core/theme/app_icons.dart';
import '../../../../../core/theme/theme_cubit.dart';
import '../../../../../injection_container.dart' as di;
import '../../data/datasources/biometric_data_source.dart';
import '../../data/datasources/local_data_source.dart';
import '../../data/services/vault_csv_import_service.dart';
import '../../domain/models/database_sync_status.dart';
import '../../domain/services/password_generator_service.dart';
import '../../domain/models/sync_conflict.dart';
import '../../domain/models/vault_custom_field.dart';
import '../../domain/models/vault_entry.dart';
import '../../domain/models/vault_group.dart';
import '../../domain/usecases/get_selected_key_file_path_usecase.dart';
import '../bloc/vault/vault_bloc.dart';
import '../bloc/vault/vault_event.dart';
import '../bloc/vault/vault_state.dart';
import '../coordinators/vault_session_coordinator.dart';
import '../widgets/internal_key_file_manager_dialog.dart';
import '../widgets/styled_info_container.dart';
import 'database_selection_screen.dart';
import 'database_unlock_screen.dart';
import 'browser_setup_screen.dart';
import '../utils/totp_utils.dart';

part 'vault/vault_shell.part.dart';
part 'vault/vault_navigation.part.dart';
part 'vault/vault_navigation_support.part.dart';
part 'vault/vault_recycle_bin.part.dart';
part 'vault/vault_entries.part.dart';
part 'vault/vault_entries_details.part.dart';
part 'vault/vault_dialogs.part.dart';
part 'vault/vault_dialog_password.part.dart';
part 'vault/vault_shared.part.dart';
