#!/usr/bin/env bash
# Mirror specs/NNN-*/ into GitHub issues and a Projects v2 board.
#
# Source of truth is the repository: spec.md gives the title, tasks.md gives the
# checklist and the status. The issue body and the board are derived, never the
# other way round -- tick the boxes in tasks.md, not in the issue.
#
# Requires: gh (authenticated), and for the board a token with Projects
# read/write (GH_TOKEN=${{ secrets.PROJECTS_TOKEN }} in CI).
#
# Usage:
#   tool/sync_spec_project.sh                 # issues + board
#   PROJECT_NUMBER= tool/sync_spec_project.sh # issues only
set -euo pipefail

cd "$(dirname "$0")/.."

REPO="${GITHUB_REPOSITORY:-$(gh repo view --json nameWithOwner -q .nameWithOwner)}"
PROJECT_OWNER="${PROJECT_OWNER:-${REPO%%/*}}"
PROJECT_NUMBER="${PROJECT_NUMBER-}"
LABEL="spec"
BODY_LIMIT=60000

gh label create "$LABEL" --repo "$REPO" --color 0E8A16 \
  --description "Spec tracked on the roadmap board" >/dev/null 2>&1 || true

# --- board metadata (optional) ----------------------------------------------
project_id=""
status_field_id=""
declare -A status_option
if [[ -n "$PROJECT_NUMBER" ]]; then
  project_id=$(gh project view "$PROJECT_NUMBER" --owner "$PROJECT_OWNER" --format json -q .id)
  fields=$(gh project field-list "$PROJECT_NUMBER" --owner "$PROJECT_OWNER" --format json --limit 50)
  status_field_id=$(jq -r '.fields[] | select(.name == "Status") | .id' <<<"$fields")
  while IFS=$'\t' read -r name id; do
    status_option["$name"]="$id"
  done < <(jq -r '.fields[] | select(.name == "Status") | .options[] | [.name, .id] | @tsv' <<<"$fields")
  if [[ -z "$status_field_id" ]]; then
    echo "Project $PROJECT_NUMBER has no Status field; skipping board updates." >&2
    project_id=""
  fi
fi

existing=$(gh issue list --repo "$REPO" --label "$LABEL" --state all --limit 200 \
  --json number,title,state)

for spec in specs/[0-9]*/spec.md; do
  dir=$(dirname "$spec")
  title=$(head -1 "$spec" | sed 's/^#[[:space:]]*//')
  id=${title%%[[:space:]]*}                      # 001, 007A, ...
  tasks="$dir/tasks.md"

  if [[ -f "$tasks" ]]; then
    total=$(grep -c '^- \[' "$tasks" || true)
    done_count=$(grep -c '^- \[[xX]\]' "$tasks" || true)
    checklist=$(awk '/^- \[/ {p=1} p' "$tasks")
    progress="**Progress:** $done_count/$total task"
  else
    total=0
    done_count=0
    checklist="_No \`tasks.md\` yet -- this spec is not broken down into tasks._"
    progress="**Progress:** not planned yet"
  fi

  if (( total > 0 && done_count == total )); then
    status="Done"
  elif (( done_count > 0 )); then
    status="In Progress"
  else
    status="Todo"
  fi

  body=$(cat <<EOF
<!-- generated by tool/sync_spec_project.sh -- edit $tasks, not this issue -->
**Spec:** [$dir/spec.md](https://github.com/$REPO/blob/main/$spec)
$progress

$checklist
EOF
)
  if (( ${#body} > BODY_LIMIT )); then
    body="${body:0:$BODY_LIMIT}"$'\n\n_Truncated -- see `'"$tasks"'` for the full list._'
  fi

  number=$(jq -r --arg id "$id " 'map(select(.title | startswith($id))) | .[0].number // empty' <<<"$existing")
  state=$(jq -r --arg id "$id " 'map(select(.title | startswith($id))) | .[0].state // empty' <<<"$existing")

  if [[ -z "$number" ]]; then
    url=$(gh issue create --repo "$REPO" --title "$title" --body "$body" --label "$LABEL")
    number=${url##*/}
    state="OPEN"
    echo "created #$number  $title"
  else
    gh issue edit "$number" --repo "$REPO" --title "$title" --body "$body" >/dev/null
    url="https://github.com/$REPO/issues/$number"
    echo "updated #$number  $title  [$status]"
  fi

  if [[ "$status" == "Done" && "$state" != "CLOSED" ]]; then
    gh issue close "$number" --repo "$REPO" --reason completed >/dev/null
  elif [[ "$status" != "Done" && "$state" == "CLOSED" ]]; then
    gh issue reopen "$number" --repo "$REPO" >/dev/null
  fi

  [[ -n "$project_id" ]] || continue
  item_id=$(gh project item-add "$PROJECT_NUMBER" --owner "$PROJECT_OWNER" --url "$url" --format json -q .id)
  option_id="${status_option[$status]-}"
  if [[ -n "$option_id" ]]; then
    gh project item-edit --id "$item_id" --project-id "$project_id" \
      --field-id "$status_field_id" --single-select-option-id "$option_id" >/dev/null
  else
    echo "  no Status option named '$status' on the board" >&2
  fi
done
