enum AppGlyph {
  add('plus'),
  back('chevron-left'),
  chevronRight('chevron-right'),
  chevronDown('chevron-down'),
  close('x'),
  more('more-vertical'),
  search('search'),
  searchOff('search-x'),
  copy('copy'),
  edit('pencil'),
  edit2('pencil'),
  delete('trash-2'),
  deleteSweep('delete-sweep'),
  warning('alert-triangle'),
  info('info'),
  check('check'),
  lock('lock'),
  fingerprint('fingerprint'),
  key('key-round'),
  eye('eye'),
  eyeOff('eye-off'),
  folder('folder'),
  folderOpen('folder'),
  folderAdd('folder-plus'),
  cloud('cloud'),
  cloudOff('cloud-off'),
  cloudDone('cloud-check'),
  sync('refresh-cw'),
  refresh('refresh-cw'),
  attachment('paperclip'),
  fileText('file-text'),
  file('file-text'),
  qrCode('qr-code'),
  magic('sparkles'),
  export('download'),
  import('upload'),
  settings('settings'),
  globe('globe'),
  linkSimple('external-link'),
  desktop('monitor'),
  sun('sun'),
  moon('moon'),
  shieldCheck('shield-check'),
  duplicates('duplicates'),
  clock('clock'),
  rowsDiff('rows-2'),
  // spec-019 DQ-8: the phone header's sort control.
  sort('arrow-up-down');

  const AppGlyph(this.assetName);

  final String assetName;

  String get assetPath => 'assets/icons/lucide/$assetName.svg';
}
